kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alpine-pvc-1g
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-1g
  labels:
    app: alpine-1g
spec:
  selector:
    matchLabels:
      app: alpine-1g
  template:
    metadata:
      labels:
        app: alpine-1g
    spec:
      containers:
      - name: alpine
        image: alpine
        args:
        - sh
        - -c
        - sleep 30d
        volumeMounts:
          - mountPath: "/tmp"
            name: alpine-pvc-1g
      volumes:
      - name: alpine-pvc-1g
        persistentVolumeClaim:
          claimName: alpine-pvc-1g
