apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpine-sts
spec:
  serviceName: alpine-sts
  replicas: 1
  selector:
    matchLabels:
      app: alpine-sts
  template:
    metadata:
      labels:
        app: alpine-sts
    spec:
      containers:
      - name: alpine-sts
        image: alpine
        args:
        - sh
        - -c
        - sleep 30d
        volumeMounts:
        - name: pvc
          mountPath: /tmp
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
